### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by nanocreaator** [toymachiner62/node-mongo-seeds#33]
I followed the README and I have this error. IS already installed all again with no success.
Any glue?
Thanks

 $> seed
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mario/.nvm/versions/node/v7.4.0/lib/node_modules/node-mongo-seeds/node_modules/mongodb/node_modules/bson/ext/index.js:15:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version

**Comment by gdeividas** [comment]
Yes please Update package dependencies..

**Comment by toymachiner62** [comment]
@gdeividas  Pull Request please?

**Comment by toymachiner62** [comment]
I updated all the dependencies to the latest versions. npm version 2.3.1 of node-mongo-seeds.
