### ISSUE TITLE
MongoError: failed to connect to server [undefined:27017] on first connect

### ISSUE THREAD

**Issue by ajbraus** [toymachiner62/node-mongo-seeds#49]
Followed instructions, got this error, but then fixed it with a hack

```
err =  { MongoError: failed to connect to server [undefined:27017] on first connect [MongoError: getaddrinfo ENOTFOUND undefined undefined:27017]
    at Pool.<anonymous> (/usr/local/lib/node_modules/node-mongo-seeds/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/usr/local/lib/node_modules/node-mongo-seeds/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Connection.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/usr/local/lib/node_modules/node-mongo-seeds/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Socket.g (events.js:292:16)
    at emitOne (events.js:96:13)
  name: 'MongoError',
  message: 'failed to connect to server [undefined:27017] on first connect [MongoError: getaddrinfo ENOTFOUND undefined undefined:27017]' }
```

my seed file:

```
process.env.NODE_ENV = "dev"
module.exports = {
	"dev": "localhost/petes-pets"
	// "prod": "localhost/PROD_DB_NAME"
}
```
This works now. Strange.

**Comment by ashokramcse** [comment]
This issue happens because of the blocking rules in the network.
